<?xml version="1.0"?>

<package format="2">

  <name>reicoures_relocalization</name>
  <version>0.0.0</version>

  <description>
    Reicoures relocalization and automatic charging package
  </description>

  <maintainer email="reicom2025@todo.todo">
    reicom2025
  </maintainer>

  <license>TODO</license>

  <!-- Build system -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- ROS dependencies -->
  <depend>roscpp</depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <depend>actionlib</depend>
  <depend>move_base_msgs</depend>

  <depend>relative_move</depend>
  <depend>ar_pose</depend>

  <export>
  </export>

</package>